# Instructions from: https://circleci.com/blog/automate-releases-from-pipelines-using-infrastructure-as-code/
# Run
---
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME_API: fgerthoffert/jav-api
      IMAGE_NAME_CLI: fgerthoffert/jav-cli
      IMAGE_NAME_UI: fgerthoffert/jav-ui
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  cli-node-latest: &cli-test
    docker:
      - image: node:latest
    working_directory: ~/cli-ci
    steps:
      - checkout
      - restore_cache: &cli-restore_cache
          keys:
            - v1-npm-cli-{{checksum ".circleci/config.yml"}}-{{checksum "cli/package-lock.json"}}
            - v1-npm-cli-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: cd cli && npm install
      - run:
          name: Linting
          command: cd cli && npm run posttest
      - run:
          name: Display version
          command: ./cli/bin/run --version
      - run:
          name: Display help
          command: ./cli/bin/run --help
      - run:
          name: Init app
          command: ./cli/bin/run init

  cli-node-8:
    <<: *cli-test
    docker:
      - image: node:8
  cli-node-10:
    <<: *cli-test
    docker:
      - image: node:10
  cli-cache:
    <<: *cli-test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd cli && npm install
      - save_cache:
          key: v1-npm-cli-{{checksum ".circleci/config.yml"}}-{{checksum "cli/package-lock.json"}}
          paths:
            - ~/cli-ci/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules

  api-node-latest: &api-test
    docker:
      - image: node:latest
    working_directory: ~/api-ci
    steps:
      - checkout
      - restore_cache: &api-restore_cache
          keys:
            - v1-npm-api-{{checksum ".circleci/config.yml"}}-{{checksum "api/package-lock.json"}}
            - v1-npm-api-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: cd api && npm install
      - run:
          name: Linting
          command: cd api && npm run lint

  api-cache:
    <<: *api-test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd api && npm install
      - save_cache:
          key: v1-npm-api-{{checksum ".circleci/config.yml"}}-{{checksum "api/package-lock.json"}}
          paths:
            - ~/api-ci/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules

  api-build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build API Docker Image
          command: cd api && docker build -t $IMAGE_NAME_API:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image_api.tar $IMAGE_NAME_API
      - persist_to_workspace:
          root: .
          paths:
            - ./image_api.tar

  api-publish-tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image_api.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_USERNAME"
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME_API:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME_API:latest
            docker push $IMAGE_NAME_API:$IMAGE_TAG

workflows:
  version: 2
  build-tags:
    jobs:
      - api-build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - api-publish-tag:
          requires:
            - api-build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  'github-indexer':
    jobs:
      - cli-node-latest
      - cli-node-10
      - cli-node-8
      - cli-cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - api-node-latest
      - api-cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
